### ISSUE TITLE
Arg newlines for Ruby

### ISSUE THREAD

**Issue by jphenow** [sportngin/styleguide#21]
IMO when you start new-lining for long method calls with args, chaining, or the like it should have a consistent style.

For chaining:

```ruby
method_call
  .method_call_2
  .method_call_3
```

For long args:

```ruby
method_call(
  :arg1,
  :arg2,
  :arg3
)
```

Thoughts? Hate? Love?

**Comment by anfleene** [comment]
Resolved in #28
